# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b469c64ba68315d7765dd80f8f69f0637bd66f2fb75356e395a44696ecba2bf915795822c9785d575cf715cb49cd1697e335ec1a65f4e5bc6a4936e52124238

test:
  secret_key_base: ed89b98f0bc034395abdb8b5a6418e837e90339ba32fbe528f5d31e79a1a3b31b1d8b35acd12e79df19acfd35bf7d8317a5775b011b0afd8db7e0848e2127269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
